name:                toan
version:             0.1.0.0
github:              "archambaultv/toan"
license:             MIT
author:              "Vincent Archambault-B"
maintainer:          "vincentarchambault@icloud.com"
copyright:           "MIT"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/archambaultv/toan#readme>

dependencies:
- base >= 4.7 && < 5
- recursion-schemes
- text
- containers
- megaparsec
- optparse-applicative
- mtl
- bifunctors
- unordered-containers
- data-fix
- comonad
- deriving-compat

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  toan:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - toan

tests:
  toan-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - toan
